spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    generate-unique-name: true
    url: jdbc:mariadb://localhost:33307/rest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      initialization-fail-fast: true
      leak-detection-threshold: 60000

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        web.servlet.mvc.method.annotation: TRACE

server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
